# k8s/log-collector-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-collector
  labels:
    app: log-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
        - name: collector
          image: log-collector:1.0
          imagePullPolicy: Never # 로컬 이미지 사용
          ports:
            - containerPort: 3001
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # 헬스체크 (선택사항)
          livenessProbe:
            httpGet:
              path: /logs
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: log-collector-service
  labels:
    app: log-collector
spec:
  selector:
    app: log-collector
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  type: ClusterIP
