apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  labels:
    app: log-generator
spec:
  replicas: 5 # 일단 5개로 시작 (20개는 나중에)
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: app
          image: log-generator:1.0
          imagePullPolicy: Never # 로컬 이미지 사용 (중요!)
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # 파드 이름 자동 주입
            - name: SERVICE_NAME
              value: "log-generator"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
